name: al_quran_fix
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  ckb_localizations: ^0.3.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  vibration: ^3.1.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/datas/
    - assets/datas/surah/
    - assets/datas/juz/
    - assets/fonts/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeRegOT.ttf
